### ISSUE TITLE
Training files

### ISSUE THREAD

**Issue by agahkarakuzu** [Notebook-Factory/QPerf_book#2]
Hey @dimitarmileski great job! I was wondering how big is this folder:

![image](https://user-images.githubusercontent.com/9632322/106357175-73c6e180-62d2-11eb-9d10-caa1bac07e41.png)

(I am checking your PR from mobile)

**Comment by dimitarmileski** [comment]
aif_training it's 915MB :)   
I forget about them. They are generated when you train the model.   I also deleted aif_detection/deployment/networks/*.pbt   
You can see [commits](https://github.com/Notebook-Factory/QPerf_book/pull/3/commits) in this pull request.

**Comment by agahkarakuzu** [comment]
@dimitarmileski we could delete this repo and create a new one without big files in history to keep it lean. Is that OK with you?

**Comment by dimitarmileski** [comment]
Yes, I agree @agahkarakuzu .
