### ISSUE TITLE
# Wierd Jekyll GitHub pages error

### ISSUE THREAD

**Issue by zelenkastiot** [Notebook-Factory/QPerf_book#4]
Hey, @agahkarakuzu @mathieuboudreau @dimitarmileski I added in settings for the repo to be built with gh-pages and got this funky looking mail:

The page build completed successfully, but returned the following warning for the `main` branch:
It looks like you're using GitHub Pages to distribute binary files. We strongly suggest that you use releases to ship projects on GitHub. Releases are GitHub's way of packaging and providing software to your users. You can think of it as a replacement to using downloads to provide software. We found the following file(s) which may be a good candidate for releases: _build/03/software/QPerf/gadgetron_QPerf_mapping.exe and content/03/software/QPerf/gadgetron_QPerf_mapping.exe. For more information, see https://docs.github.com/github/administering-a-repository/about-releases.

For information on troubleshooting Jekyll see:

  https://docs.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can submit a request on the Contact GitHub page at https://support.github.com/contact?repo_id=325407728&page_build_id=230387232

**Comment by dimitarmileski** [comment]
Hey @zelenkastiot.   
In "content/03/software/QPerf" there are executable files from the QPerf software. I put them to ensure reproducibility of that part of the code. But other solution is to delete folder "content/03/software/QPerf"  and give link to [QPerf](https://gadgetrondata.blob.core.windows.net/gadgetrongithubio/files/QPerf/QPerf.zip). And after that if someone want to run [Perfusion Flow Mapping](https://dimitarmileski.github.io/QPerf_book/03/Run_QPerf_SOS.html) they should download the software, upload to running Binder instance in folder "content/03/software/QPerf", and run the code.

GitHubPages gives warning for distributing binary files, but it's not an error, the page is rendered how it should be.
